name: Continuous Integration

on: [push]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build library ZIP
      run: |
        mkdir BlenderServoAnimation
        cp -R src examples library.properties README.md LICENSE BlenderServoAnimation
        zip -r blender_servo_animation_arduino_library BlenderServoAnimation
    - name: Archive library ZIP
      uses: actions/upload-artifact@v3
      with:
        name: blender_servo_animation_arduino_library.zip
        path: |
          blender_servo_animation_arduino_library.zip
  lint:
    name: "Lint"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y clang-format-13
    - name: Lint with clang-format
      run: |
        find src test -regex '.*\.\(cpp\|h\)' -exec clang-format-13 --dry-run --Werror {} \;
        find examples -regex '.*\.ino' -exec clang-format-13 --dry-run --Werror {} \;
    - uses: arduino/arduino-lint-action@v1
  test:
    name: "Test"
    runs-on: ubuntu-latest
    env:
      LD_LIBRARY_PATH: /home/runner/.platformio/packages/tool-simavr/lib
    steps:
    - uses: actions/checkout@v3
    - name: Cache PlatformIO directory
      uses: actions/cache@v3
      with:
        path: /home/runner/.platformio
        key: platformio-dir
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pip'
        cache-dependency-path: requirements-dev.txt
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y libelf-dev
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Run tests with platformio
      run: |
        pio test --without-uploading
